version: "3.5"

services:
  db:
    image: mariadb:10.5
    restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: tobapi
      MYSQL_DATABASE: clanwolf
      MYSQL_USER: tobapi_user
      MYSQL_PASSWORD: tobapi_pass
    container_name: tob_mariadb
    networks:
    - traefik

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080
    container_name: tob_adminer
    networks:
    - traefik

  web:
    image: php:7.4-cli
    labels:
    - "traefik.http.routers.tob-web.rule=Host(`tob.local`)"
    - "traefik.http.routers.tob-web.tls=false"
    - "traefik.http.services.tob-web.loadbalancer.server.port=8080"
    volumes:
    - "./web:/code"
    working_dir: /code
    command: php -S 0.0.0.0:8080
    container_name: tob_web
    networks:
    - traefik

networks:
  traefik:
    external: true
