version: "3"

services:
  db:
    image: mariadb:10.5
    restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: tobapi
      MYSQL_DATABASE: clanwolf
      MYSQL_USER: tobapi_user
      MYSQL_PASSWORD: tobapi_pass
    container_name: mariadb

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080
    container_name: adminer
